import React, { useEffect, useState } from 'react';
import { Activity, BarChart3, CheckCircle2, Clock3, DollarSign, Percent, RefreshCw, Users, XCircle } from 'lucide-react';
import { apiUrl } from '../api/client';

type Period = '7d' | '30d' | '12m';
type Analytics = { period: Period; kpis: { revenue: number | null; activeUsers: number; conversions: number | null; retention: number | null; activeCampaigns: number }; trend: { label: string; clients: number; campaigns: number; aiRequests: number }[]; distribution: { category: string; value: number }[]; activity: { id: string; action: string; entity: string; userName: string; createdAt: string; status: string }[] };

const money = (v: number | null) => v === null ? '—' : new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 }).format(v);
const number = (v: number | null) => v === null ? '—' : new Intl.NumberFormat('pt-BR').format(v);
const percent = (v: number | null) => v === null ? '—' : v.toFixed(1) + '%';
const label = (v: string) => ({ CAMPAIGN_CREATED: 'Campanha criada', CAMPAIGN_UPDATED: 'Campanha atualizada', CAMPAIGN_ACTIVATED: 'Campanha ativada', CAMPAIGN_DEACTIVATED: 'Campanha pausada', CAMPAIGN_STRATEGY_GENERATED: 'Estratégia gerada', CLIENT_CREATED: 'Empresa cadastrada', CLIENT_UPDATED: 'Empresa atualizada', CLIENT_DELETED: 'Empresa excluída' } as Record<string,string>)[v] || v.replaceAll('_', ' ');

const Skeleton = ({ className }: { className: string }) => <div className={'animate-pulse rounded-xl bg-zinc-800/70 ' + className} />;

const Kpi = ({ title, value, icon: Icon, tone, unavailable }: { title: string; value: string; icon: React.ElementType; tone: string; unavailable?: boolean }) => <article className='rounded-2xl border border-white/[0.07] bg-zinc-900/80 p-5'><div className='flex items-start justify-between'><div><p className='text-[11px] font-semibold uppercase tracking-wider text-zinc-500'>{title}</p><p className='mt-3 text-2xl font-bold text-white'>{value}</p></div><div className={'rounded-xl p-2.5 ' + tone}><Icon className='h-5 w-5' /></div></div><p className='mt-4 text-[10px] text-zinc-500'>{unavailable ? 'Métrica ainda não integrada' : 'Dados atuais'}</p></article>;

const Trend = ({ data }: { data: Analytics['trend'] }) => { const w=760,h=280,px=34,py=24; const max=Math.max(1,...data.flatMap(x=>[x.clients,x.campaigns,x.aiRequests])); const X=(i:number)=>px+(i/Math.max(1,data.length-1))*(w-px*2); const Y=(v:number)=>h-py-(v/max)*(h-py*2); const path=(key:'clients'|'campaigns'|'aiRequests')=>data.map((x,i)=>(i?'L ':'M ')+X(i).toFixed(1)+' '+Y(x[key]).toFixed(1)).join(' '); return <div className='overflow-x-auto'><svg viewBox={'0 0 '+w+' '+h} className='h-[280px] min-w-[680px] w-full'><path d={path('clients')} fill='none' stroke='#818cf8' strokeWidth='3'/><path d={path('campaigns')} fill='none' stroke='#22d3ee' strokeWidth='3'/><path d={path('aiRequests')} fill='none' stroke='#a78bfa' strokeWidth='3'/>{data.map((x,i)=><g key={x.label}><circle cx={X(i)} cy={Y(x.clients)} r='4' fill='#818cf8'><title>{x.label + ': ' + x.clients + ' empresas'}</title></circle><circle cx={X(i)} cy={Y(x.campaigns)} r='4' fill='#22d3ee'><title>{x.label + ': ' + x.campaigns + ' campanhas'}</title></circle><circle cx={X(i)} cy={Y(x.aiRequests)} r='4' fill='#a78bfa'><title>{x.label + ': ' + x.aiRequests + ' solicitações IA'}</title></circle></g>)}</svg></div>; };

export const AnalyticsDashboard: React.FC<{ jwtToken: string }> = ({ jwtToken }) => {
 const [period,setPeriod]=useState<Period>('30d'); const [data,setData]=useState<Analytics|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch(apiUrl('/api/analytics?period='+period),{headers:{Authorization:'Bearer '+jwtToken}});const j=await r.json();if(!r.ok)throw new Error(j.error||'Falha ao carregar analytics.');setData(j.data);}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar analytics.');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[jwtToken,period]);
 return <div className='space-y-6'>
  <header className='flex flex-col gap-4 rounded-2xl border border-white/[0.07] bg-zinc-900/80 p-5 sm:flex-row sm:items-center sm:justify-between'><div><div className='flex items-center gap-2'><BarChart3 className='h-5 w-5 text-indigo-400'/><h2 className='text-xl font-bold text-white'>Analytics & Métricas</h2><span className='rounded-full bg-emerald-500/10 px-2 py-1 text-[10px] font-semibold text-emerald-400'>● Operacional</span></div><p className='mt-1 text-xs text-zinc-500'>Visão consolidada da operação da agência com dados do tenant.</p></div><div className='flex gap-2'><select value={period} onChange={e=>setPeriod(e.target.value as Period)} className='min-h-11 rounded-xl border border-white/[0.07] bg-zinc-950 px-3 text-xs text-white'><option value='7d'>Últimos 7 dias</option><option value='30d'>Últimos 30 dias</option><option value='12m'>Últimos 12 meses</option></select><button type='button' onClick={()=>void load()} disabled={loading} className='flex min-h-11 items-center gap-2 rounded-xl border border-white/[0.07] bg-zinc-950 px-3 text-xs text-zinc-300'><RefreshCw className={'h-3.5 w-3.5 '+(loading?'animate-spin':'')}/><span className='hidden sm:inline'>Atualizar</span></button></div></header>
  {error && <div className='rounded-xl border border-rose-500/20 bg-rose-500/10 px-4 py-3 text-xs text-rose-300'>{error}</div>}
  <section className='grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4'>{loading||!data ? [1,2,3,4].map(x=><Skeleton key={x} className='h-36'/>):<><Kpi title='Receita Total' value={money(data.kpis.revenue)} icon={DollarSign} tone='bg-emerald-500/10 text-emerald-400' unavailable={data.kpis.revenue===null}/><Kpi title='Usuários Ativos' value={number(data.kpis.activeUsers)} icon={Users} tone='bg-indigo-500/10 text-indigo-400'/><Kpi title='Conversões' value={number(data.kpis.conversions)} icon={CheckCircle2} tone='bg-cyan-500/10 text-cyan-400' unavailable={data.kpis.conversions===null}/><Kpi title='Taxa de Retenção' value={percent(data.kpis.retention)} icon={Percent} tone='bg-violet-500/10 text-violet-400' unavailable={data.kpis.retention===null}/></>}</section>
  <section className='grid gap-4 xl:grid-cols-[minmax(0,1.7fr)_minmax(300px,0.8fr)]'><article className='rounded-2xl border border-white/[0.07] bg-zinc-900/80 p-5'><div className='flex flex-wrap items-center justify-between gap-3'><div><h3 className='text-sm font-bold text-white'>Evolução operacional</h3><p className='mt-1 text-[11px] text-zinc-500'>Empresas, campanhas e solicitações de IA.</p></div><div className='flex gap-3 text-[10px] text-zinc-400'><span>● Empresas</span><span>● Campanhas</span><span>● IA</span></div></div><div className='mt-4'>{loading||!data?<Skeleton className='h-[280px]'/>:<Trend data={data.trend}/>}</div></article>
  <article className='rounded-2xl border border-white/[0.07] bg-zinc-900/80 p-5'><div className='flex items-center gap-2'><Activity className='h-4 w-4 text-violet-400'/><div><h3 className='text-sm font-bold text-white'>Distribuição por status</h3><p className='text-[11px] text-zinc-500'>Campanhas por estágio atual.</p></div></div><div className='mt-6 space-y-4'>{loading||!data?<Skeleton className='h-48'/>:data.distribution.length===0?<p className='rounded-xl border border-dashed border-white/[0.07] p-8 text-center text-xs text-zinc-500'>Nenhuma campanha registrada.</p>:data.distribution.map(x=><div key={x.category}><div className='mb-1.5 flex justify-between text-xs'><span className='text-zinc-300'>{x.category}</span><b className='text-white'>{x.value}</b></div><div className='h-2 rounded-full bg-zinc-800'><div className='h-2 rounded-full bg-gradient-to-r from-indigo-500 to-violet-500' style={{width:Math.min(100,x.value/Math.max(1,...data.distribution.map(y=>y.value))*100)+'%'}}/></div></div>)}</div></article></section>
  <section className='rounded-2xl border border-white/[0.07] bg-zinc-900/80 p-5'><div className='flex items-center justify-between'><div><h3 className='text-sm font-bold text-white'>Atividades recentes</h3><p className='mt-1 text-[11px] text-zinc-500'>Últimas ações registradas na operação.</p></div><Clock3 className='h-4 w-4 text-zinc-500'/></div><div className='mt-4 space-y-2'>{loading||!data?[1,2,3,4,5].map(x=><Skeleton key={x} className='h-14'/>):data.activity.length===0?<p className='p-8 text-center text-xs text-zinc-500'>Nenhuma atividade registrada.</p>:data.activity.map(x=><div key={x.id} className='flex items-center gap-3 rounded-xl border border-white/[0.05] bg-zinc-950/60 p-3'><div className='flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-indigo-500/10 text-[10px] font-bold text-indigo-300'>{x.userName.split(' ').map(v=>v[0]).slice(0,2).join('').toUpperCase()}</div><div className='min-w-0 flex-1'><p className='truncate text-xs font-semibold text-zinc-200'>{label(x.action)}</p><p className='truncate text-[10px] text-zinc-500'>{x.userName} • {x.entity}</p></div>{x.status==='ERROR'?<XCircle className='h-4 w-4 text-rose-400'/>:<CheckCircle2 className='h-4 w-4 text-emerald-400'/>}<time className='shrink-0 text-[10px] text-zinc-600'>{new Date(x.createdAt).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</time></div>)}</div></section>
  <p className='text-[10px] text-zinc-600'>Receita, conversões e retenção ficam como indisponíveis enquanto esses eventos não forem registrados pelo produto.</p>
 </div>;
}